### ISSUE TITLE
trying this again

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/components-on-a-grid#1]
@thatkidmadrid
Finally was able to get a bunch more done, though I still can't get the bottom images side-by-side or the white text in the top right corner of the top image. What's worst is now it's 63% different, when it looks so much closer.

**Comment by thatkidmadrid** [comment]
Take a look at the css grid cheatsheet https://learn-the-web.algonquindesign.ca/topics/css-grid-cheat-sheet/ for some hints on how to position those items. I can see you're on the right track. It also helps to rewatch the videos to find the specific thing you're trying to do.

**Comment by Jessica-Lee123** [comment]
@thatkidmadrid 
The class helped a lot, the only thing I'm having trouble finding now is why both images are in one column. I'm down to 32% difference still.

**Comment by Jessica-Lee123** [comment]
[carboni-jessica-030-grid-recording.m4a.zip](https://github.com/Jessica-Lee123/components-on-a-grid/files/7240197/carboni-jessica-030-grid-recording.m4a.zip)
@thatkidmadrid 
Please let me know if this worked, seems sketch to me...

**Comment by thatkidmadrid** [comment]
I think overall you spoke the code well!
Just remember to start each selection by saying "select" or "target" so it's clear to the listener that you're selecting a different element
I think you got pretty close several times before I steered you in a better direction so don't feel discouraged. This takes practice, and i understand especially remotely, it's tough to get the same type of technical support while learning
